using ConnectHub.ChatRoom.Hubs;
using ConnectHub.ChatRoom.Controllers;
using ConnectHub.ChatRoom.Data;
using ConnectHub.ChatRoom.Middleware;
using ConnectHub.ChatRoom.Models.DTOs;
using ConnectHub.ChatRoom.Models.Entities;
using ConnectHub.ChatRoom.Models.Events;
using ConnectHub.ChatRoom.Repositories.Implementations;
using ConnectHub.ChatRoom.Repositories.Interfaces;
using ConnectHub.ChatRoom.Services.Implementations;
using ConnectHub.ChatRoom.Services.Interfaces;
// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConnectHub.ChatRoom.Migrations;
    [DbContext(typeof(ChatRoomDbContext))]
    [Migration("20260514100227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("chatroom")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConnectHub.ChatRoom.Models.Entities.ChatRoom", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMessageContent")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("PUBLIC");

                    b.HasKey("RoomId");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_ChatRooms_CreatedByUserId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_ChatRooms_DeletedAt");

                    b.HasIndex("RoomType", "IsActive")
                        .HasDatabaseName("IX_ChatRooms_RoomType_IsActive");

                    b.ToTable("ChatRooms", "chatroom");
                });

            modelBuilder.Entity("ConnectHub.ChatRoom.Models.Entities.RoomInvite", b =>
                {
                    b.Property<int>("InviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InviteId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("InvitedUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING");

                    b.HasKey("InviteId");

                    b.HasIndex("InvitedUserId", "Status")
                        .HasDatabaseName("IX_RoomInvites_InvitedUserId_Status");

                    b.HasIndex("RoomId", "InvitedUserId", "Status")
                        .HasDatabaseName("IX_RoomInvites_RoomId_UserId_Status");

                    b.ToTable("RoomInvites", "chatroom");
                });

            modelBuilder.Entity("ConnectHub.ChatRoom.Models.Entities.RoomMember", b =>
                {
                    b.Property<int>("RoomMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomMemberId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("MEMBER");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RoomMemberId");

                    b.HasIndex("RoomId", "Role")
                        .HasDatabaseName("IX_RoomMembers_RoomId_Role");

                    b.HasIndex("RoomId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_RoomMembers_RoomId_UserId");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_RoomMembers_UserId_IsActive");

                    b.ToTable("RoomMembers", "chatroom");
                });

            modelBuilder.Entity("ConnectHub.ChatRoom.Models.Entities.RoomInvite", b =>
                {
                    b.HasOne("ConnectHub.ChatRoom.Models.Entities.ChatRoom", "Room")
                        .WithMany("Invites")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConnectHub.ChatRoom.Models.Entities.RoomMember", b =>
                {
                    b.HasOne("ConnectHub.ChatRoom.Models.Entities.ChatRoom", "Room")
                        .WithMany("Members")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConnectHub.ChatRoom.Models.Entities.ChatRoom", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }



